# Generated by Django 3.1.7 on 2021-05-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='saiteja',
        ),
    ]
