# Generated by Django 3.1.7 on 2021-05-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0002_auto_20210509_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pass1',
            new_name='passw',
        ),
    ]
