from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name='home-page'),
    path('home1',views.home1),
    path('login', views.login),
    path('signup', views.signup),
    path('aboutus', views.aboutus),
    path('contactus',views.contactus),
    path('aboutus',views.aboutus),
    path('netbanking',views.netbanking),
    path('netbanking1',views.netbanking1),
    path('netbankingoperations',views.netbankingoperations),
    path('netbankingregister',views.netbankingregister),
    path('personalbanking',views.personalbanking),
    path('personalbanking1',views.personalbanking1),
    path('personalbankingoperations',views.pesronalbankingoperations),
    path('vehicleloan',views.vehicleloan),
    path('educationloan',views.educationloan),
    path('homeloan',views.homeloan),
    path('accounttransaction',views.accounttransaction),
    path('lifeinsurance',views.lifeinsurance),
    path('healthinsurance',views.healthinsurance),
    path('vehicleinsurance',views.vehicleinsurance),
    path('mobilerecharge',views.mobilerecharge),
    path('fastag',views.fastag),
    path('cabletv',views.cabletv),
    path('broadband',views.broadband),
    path('postpaid',views.postpaid),
    path('electricitybills',views.electricitybills),
    path('educationfee',views.educationfee),
    path('donateoxygen',views.donateoxygen),
    path('applyloans',views.applyloans),
    path('applyloans1',views.applyloans1),
    path('fixeddeposits',views.fixeddeposits),
    path('insurance',views.insurance),
    path('insurance1',views.insurance1),
    path('post', views.createpost),
    path('log',views.createlogin),
    path('mobilerecharge1',views.createmobilerecharge),
    path('fastagrecharge',views.createfastag),
    path('cabletvrecharge',views.createcabletv),
    path('broadbandrecharge',views.createbroadband),
    path('electricbills',views.createelectricbills),
    path('payeducationfee',views.createeducationfee1),
    path('paypostpaid',views.createpostpaid),
    path('paydonateoxygen',views.createdonateoxygen),
    path('applyhomeloan1',views.createhomeloan1),
    path('applyeducationloan1',views.createeducationloan1),
    path('applyvehicleloan1',views.createvehicleloan1),
    path('applyaccounttoaccount',views.createaccounttoaccount),
    path('contactus1',views.createcontactus),
    path('applyloans2',views.createapplyloan),
    path('applylifeinsurance',views.createlifeinsurance),
    path('applyvehicleinsurance',views.createvehicleinsurance),
    path('history',views.history),
    path('mywallet',views.mywallet),
    path('makepayments1',views.mobilerechargepayment),
    path('makepayments2',views.oxygendonapepayment),
]